//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTORY CLEANING.
        /// </summary>
        internal static string btnCleanLabelRes {
            get {
                return ResourceManager.GetString("btnCleanLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET CONFIG.
        /// </summary>
        internal static string btnConfigLabelRes {
            get {
                return ResourceManager.GetString("btnConfigLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose destination directory.
        /// </summary>
        internal static string btnDestinationDirRes {
            get {
                return ResourceManager.GetString("btnDestinationDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICK UP WINDOWS MAIL EMAIL DIRECTORY.
        /// </summary>
        internal static string btnDirectoryLabelRes {
            get {
                return ResourceManager.GetString("btnDirectoryLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose directory containing Windows Mail files (application is trying to guess).
        /// </summary>
        internal static string btnDirectoryScreenRes {
            get {
                return ResourceManager.GetString("btnDirectoryScreenRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUCTIONS.
        /// </summary>
        internal static string btnHelpLabelRes {
            get {
                return ResourceManager.GetString("btnHelpLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORT TO OUTLOOK.
        /// </summary>
        internal static string btnImportLabelRes {
            get {
                return ResourceManager.GetString("btnImportLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import mails from Windows Mail to Outlook.
        /// </summary>
        internal static string btnImportScreenRes {
            get {
                return ResourceManager.GetString("btnImportScreenRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYNC ONLINE.
        /// </summary>
        internal static string btnSyncLabelRes {
            get {
                return ResourceManager.GetString("btnSyncLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose number of days to synchronize.
        /// </summary>
        internal static string cmbTextChooseOption {
            get {
                return ResourceManager.GetString("cmbTextChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string credInitialUserName {
            get {
                return ResourceManager.GetString("credInitialUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username and password.
        /// </summary>
        internal static string credMessage {
            get {
                return ResourceManager.GetString("credMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into EAS server.
        /// </summary>
        internal static string credTitle {
            get {
                return ResourceManager.GetString("credTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during deserialization, check output directory for text files. Click OK to continue.
        /// </summary>
        internal static string errSerialization {
            get {
                return ResourceManager.GetString("errSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string GenericErrorRes {
            get {
                return ResourceManager.GetString("GenericErrorRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning.
        /// </summary>
        internal static string grpCleaningLabelRes {
            get {
                return ResourceManager.GetString("grpCleaningLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string grpHelpLabelRes {
            get {
                return ResourceManager.GetString("grpHelpLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        internal static string grpImportLabelRes {
            get {
                return ResourceManager.GetString("grpImportLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string grpInformationLabelRes {
            get {
                return ResourceManager.GetString("grpInformationLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        internal static string grpKonwersjaLabelRes {
            get {
                return ResourceManager.GetString("grpKonwersjaLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick required directory up.
        /// </summary>
        internal static string lblChooseOption {
            get {
                return ResourceManager.GetString("lblChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAN&apos;T DELETE FILES.
        /// </summary>
        internal static string lblTotalDelNotRes {
            get {
                return ResourceManager.GetString("lblTotalDelNotRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESSFULLY DELETED FILES.
        /// </summary>
        internal static string lblTotalDelSuccessRes {
            get {
                return ResourceManager.GetString("lblTotalDelSuccessRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR DELETING .
        /// </summary>
        internal static string lblTotalErrorDeletingRes {
            get {
                return ResourceManager.GetString("lblTotalErrorDeletingRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: .
        /// </summary>
        internal static string lblTotalGenericErrorRes {
            get {
                return ResourceManager.GetString("lblTotalGenericErrorRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - no MAPI files inside directory.
        /// </summary>
        internal static string lblTotalNoFilesInsideDirRes {
            get {
                return ResourceManager.GetString("lblTotalNoFilesInsideDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t picked up remote folder to synchronize with.
        /// </summary>
        internal static string remoteFolderErrToSync {
            get {
                return ResourceManager.GetString("remoteFolderErrToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string settingsBtnCancel {
            get {
                return ResourceManager.GetString("settingsBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string settingsBtnOK {
            get {
                return ResourceManager.GetString("settingsBtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is MSExchane?.
        /// </summary>
        internal static string settingsCbExchange {
            get {
                return ResourceManager.GetString("settingsCbExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOCKED.
        /// </summary>
        internal static string settingsChkUnblock {
            get {
                return ResourceManager.GetString("settingsChkUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVICE.
        /// </summary>
        internal static string settingsLblDevice {
            get {
                return ResourceManager.GetString("settingsLblDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROTOCOL.
        /// </summary>
        internal static string settingsLblProtocol {
            get {
                return ResourceManager.GetString("settingsLblProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER.
        /// </summary>
        internal static string settingsLblServer {
            get {
                return ResourceManager.GetString("settingsLblServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        internal static string settingsLblUsername {
            get {
                return ResourceManager.GetString("settingsLblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete config information: Server address and protocol version and device id.
        /// </summary>
        internal static string settingsMess {
            get {
                return ResourceManager.GetString("settingsMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin settings.
        /// </summary>
        internal static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing violation error, try restart Outlook.
        /// </summary>
        internal static string sharingViolationError {
            get {
                return ResourceManager.GetString("sharingViolationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DELETING FILE .
        /// </summary>
        internal static string strDeletingFileRes {
            get {
                return ResourceManager.GetString("strDeletingFileRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUPLICATES FOUND INSIDE DIRECTORY .
        /// </summary>
        internal static string strDuplicatesInsideDirectoryRes {
            get {
                return ResourceManager.GetString("strDuplicatesInsideDirectoryRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EMAIL FETCHED.
        /// </summary>
        internal static string strEmailsDownloaded {
            get {
                return ResourceManager.GetString("strEmailsDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAILS INSIDE CHOOSEN DIRECTORY.
        /// </summary>
        internal static string strEmailsInsideChoosenDirRes {
            get {
                return ResourceManager.GetString("strEmailsInsideChoosenDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAILS IN CHOOSEN OUTLOOK DIR .
        /// </summary>
        internal static string strEmailsInsideChoosenOutlookDirRes {
            get {
                return ResourceManager.GetString("strEmailsInsideChoosenOutlookDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EMAILS ON SERVER.
        /// </summary>
        internal static string strEmailsToSync {
            get {
                return ResourceManager.GetString("strEmailsToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FILES INSIDE DIRECTORY.
        /// </summary>
        internal static string strFilesInsideDirectoryRes {
            get {
                return ResourceManager.GetString("strFilesInsideDirectoryRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FILES TO DELETE .
        /// </summary>
        internal static string strFilesToDeleteRes {
            get {
                return ResourceManager.GetString("strFilesToDeleteRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails to add.
        /// </summary>
        internal static string strMailsToAddRes {
            get {
                return ResourceManager.GetString("strMailsToAddRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MAPI FILES.
        /// </summary>
        internal static string strMapiFilesInsideDirectoryRes {
            get {
                return ResourceManager.GetString("strMapiFilesInsideDirectoryRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MIME FILES.
        /// </summary>
        internal static string strMimeFilesInsideDirectoryRes {
            get {
                return ResourceManager.GetString("strMimeFilesInsideDirectoryRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW EMAILS INSIDE OUTLOOK DIR.
        /// </summary>
        internal static string strNewEmailsInsideOutlookDirRes {
            get {
                return ResourceManager.GetString("strNewEmailsInsideOutlookDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected local folder doesn&apos;t contain email files.
        /// </summary>
        internal static string strNoEmlInside {
            get {
                return ResourceManager.GetString("strNoEmlInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORTING ELEMENT NUMBER.
        /// </summary>
        internal static string strSortElementNumberRes {
            get {
                return ResourceManager.GetString("strSortElementNumberRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during synchronization, full mode has been set, try again.
        /// </summary>
        internal static string strSyncProvision {
            get {
                return ResourceManager.GetString("strSyncProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username and/or password.
        /// </summary>
        internal static string strSyncWrongUserPass {
            get {
                return ResourceManager.GetString("strSyncWrongUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe requested, try sync again.
        /// </summary>
        internal static string strWipeReq {
            get {
                return ResourceManager.GetString("strWipeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIL SYNC.
        /// </summary>
        internal static string tabSyncLabelRes {
            get {
                return ResourceManager.GetString("tabSyncLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change only in case no synchronization is possible, otherwise your account is going to have many devices tied.
        /// </summary>
        internal static string tooltipCheckboxSettings {
            get {
                return ResourceManager.GetString("tooltipCheckboxSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol version, for example 14.
        /// </summary>
        internal static string tooltipProtocolSettings {
            get {
                return ResourceManager.GetString("tooltipProtocolSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address for example server.eas.uk.
        /// </summary>
        internal static string tooltipServerSettings {
            get {
                return ResourceManager.GetString("tooltipServerSettings", resourceCulture);
            }
        }
    }
}
