//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTORY CLEANING.
        /// </summary>
        internal static string btnCleanLabelRes {
            get {
                return ResourceManager.GetString("btnCleanLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose destination directory.
        /// </summary>
        internal static string btnDestinationDirRes {
            get {
                return ResourceManager.GetString("btnDestinationDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICK UP WINDOWS MAIL EMAIL DIRECTORY.
        /// </summary>
        internal static string btnDirectoryLabelRes {
            get {
                return ResourceManager.GetString("btnDirectoryLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose directory containing Windows Mail files (application is trying to guess).
        /// </summary>
        internal static string btnDirectoryScreenRes {
            get {
                return ResourceManager.GetString("btnDirectoryScreenRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUCTIONS.
        /// </summary>
        internal static string btnHelpLabelRes {
            get {
                return ResourceManager.GetString("btnHelpLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORT TO OUTLOOK.
        /// </summary>
        internal static string btnImportLabelRes {
            get {
                return ResourceManager.GetString("btnImportLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import mails from Windows Mail to Outlook.
        /// </summary>
        internal static string btnImportScreenRes {
            get {
                return ResourceManager.GetString("btnImportScreenRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string GenericErrorRes {
            get {
                return ResourceManager.GetString("GenericErrorRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning.
        /// </summary>
        internal static string grpCleaningLabelRes {
            get {
                return ResourceManager.GetString("grpCleaningLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string grpHelpLabelRes {
            get {
                return ResourceManager.GetString("grpHelpLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        internal static string grpImportLabelRes {
            get {
                return ResourceManager.GetString("grpImportLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string grpInformationLabelRes {
            get {
                return ResourceManager.GetString("grpInformationLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        internal static string grpKonwersjaLabelRes {
            get {
                return ResourceManager.GetString("grpKonwersjaLabelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAN&apos;T DELETE FILES.
        /// </summary>
        internal static string lblTotalDelNotRes {
            get {
                return ResourceManager.GetString("lblTotalDelNotRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESSFULLY DELETED FILES.
        /// </summary>
        internal static string lblTotalDelSuccessRes {
            get {
                return ResourceManager.GetString("lblTotalDelSuccessRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR DELETING .
        /// </summary>
        internal static string lblTotalErrorDeletingRes {
            get {
                return ResourceManager.GetString("lblTotalErrorDeletingRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: .
        /// </summary>
        internal static string lblTotalGenericErrorRes {
            get {
                return ResourceManager.GetString("lblTotalGenericErrorRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - no MAPI files inside directory.
        /// </summary>
        internal static string lblTotalNoFilesInsideDirRes {
            get {
                return ResourceManager.GetString("lblTotalNoFilesInsideDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DELETING FILE .
        /// </summary>
        internal static string strDeletingFileRes {
            get {
                return ResourceManager.GetString("strDeletingFileRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUPLICATES FOUND INSIDE DIRECTORY .
        /// </summary>
        internal static string strDuplicatesInsideDirectoryRes {
            get {
                return ResourceManager.GetString("strDuplicatesInsideDirectoryRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAILS INSIDE CHOOSEN DIRECTORY.
        /// </summary>
        internal static string strEmailsInsideChoosenDirRes {
            get {
                return ResourceManager.GetString("strEmailsInsideChoosenDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAILS IN CHOOSEN OUTLOOK DIR .
        /// </summary>
        internal static string strEmailsInsideChoosenOutlookDirRes {
            get {
                return ResourceManager.GetString("strEmailsInsideChoosenOutlookDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FILES INSIDE DIRECTORY.
        /// </summary>
        internal static string strFilesInsideDirectoryRes {
            get {
                return ResourceManager.GetString("strFilesInsideDirectoryRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FILES TO DELETE .
        /// </summary>
        internal static string strFilesToDeleteRes {
            get {
                return ResourceManager.GetString("strFilesToDeleteRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails to add.
        /// </summary>
        internal static string strMailsToAddRes {
            get {
                return ResourceManager.GetString("strMailsToAddRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MAPI FILES.
        /// </summary>
        internal static string strMapiFilesInsideDirectoryRes {
            get {
                return ResourceManager.GetString("strMapiFilesInsideDirectoryRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MIME FILES.
        /// </summary>
        internal static string strMimeFilesInsideDirectoryRes {
            get {
                return ResourceManager.GetString("strMimeFilesInsideDirectoryRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW EMAILS INSIDE OUTLOOK DIR.
        /// </summary>
        internal static string strNewEmailsInsideOutlookDirRes {
            get {
                return ResourceManager.GetString("strNewEmailsInsideOutlookDirRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORTING ELEMENT NUMBER.
        /// </summary>
        internal static string strSortElementNumberRes {
            get {
                return ResourceManager.GetString("strSortElementNumberRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIL SYNC.
        /// </summary>
        internal static string tabSyncLabelRes {
            get {
                return ResourceManager.GetString("tabSyncLabelRes", resourceCulture);
            }
        }
    }
}
